### ISSUE TITLE
Responsive img

### ISSUE THREAD

**Issue by evilebottnawi** [coliff/bootstrap-ie7#28]
``` css
img{width:auto;height:auto;-ms-interpolation-mode:bicubic}
```

But not all image responsible, may be usage .img-responsive instead all img
